Feature/adwords
vtex-apps/google-adwords pull request #1
Opened 2018-09-11 18:14 UTC by andreldsa

2018-09-18 02:05 UTC, vitoriaHeliane commented on react/index.js
> +  productView = (event) => {
Remove the parentheses.

2018-09-18 02:05 UTC, vitoriaHeliane commented on react/index.js
> +    const skuId = event.products[0].id
I think this can cause an exception, so you should check if the products isn't undefined before access the element.

2018-09-18 02:05 UTC, vitoriaHeliane commented on react/index.js
> +  departmentView = (event) => {
Remove the parentheses.

2018-09-18 02:05 UTC, vitoriaHeliane commented on react/index.js
> +        <script async src={`https://www.googletagmanager.com/gtag/js?id=${this.adwordsID}`}></script>
<script ... />

2018-09-18 02:05 UTC, vitoriaHeliane commented on react/index.js
> +  context: PropTypes.object
The comman is missing.

2018-09-18 17:53 UTC, brunojdo reviewed
CHANGELOG

2018-09-18 17:53 UTC, brunojdo approved these changes

2018-09-18 18:13 UTC, brunojdo requested changes

2018-09-18 18:13 UTC, brunojdo commented on manifest.json
> +  "title": "Google Adwords",
google-adwords

2018-09-18 18:13 UTC, brunojdo commented on README.md
> +    }
See an example in Dreamstore(pages.json link)

2018-09-18 18:13 UTC, brunojdo commented on react/index.js
> +
remove blank lines

2018-09-18 18:13 UTC, brunojdo commented on react/index.js
> +class Adwords extends Component {
docs

2018-09-18 18:13 UTC, brunojdo commented on react/index.js
> +  getSettings: PropTypes.func,
docs

2018-09-24 16:13 UTC, brunojdo requested changes

2018-09-24 16:13 UTC, brunojdo commented on CHANGELOG.md
> + - Initial files and logic created.
MVP of Google Adwords

2018-09-24 16:13 UTC, brunojdo commented on react/index.js
> +  departmentView = event => {
remove

2018-09-24 16:16 UTC, lucis requested changes

2018-09-24 16:16 UTC, luciannojunior commented on react/index.js
> +    dataLayer.push(data)
I think it's preferable to explicitly use `window.dataLayer` instead

2018-09-24 16:16 UTC, luciannojunior commented on react/index.js
> +  departmentView = event => {
Is it a TODO?

2018-09-24 17:01 UTC, claudivanfilho approved these changes

2018-09-24 18:06 UTC, gugabribeiro approved these changes

2018-09-24 19:39 UTC, lucis approved these changes

2018-09-26 16:50 UTC, brunojdo approved these changes

2018-09-26 16:50 UTC, brunojdo commented on README.md
> +    "vtex.adwords": "0.x"
vtex.google-adwords

2018-09-26 17:33 UTC, brunojdo approved these changes

2018-09-26 17:55 UTC, merged