Migrate app to typescript
vtex-apps/google-adwords pull request #2
Opened 2018-10-04 12:56 UTC by lucasecdb

2018-10-04 18:12 UTC, salesfelipe requested changes

2018-10-04 18:12 UTC, salesfelipe commented on react/index.tsx
> +    getSettings: PropTypes.func,
Shouldn´t this be on the interface as well?

2018-10-04 20:24 UTC, lucasecdb commented on react/index.tsx
> +    getSettings: PropTypes.func,
there's no definition for the context type on the `Component` :-(

2018-10-05 12:09 UTC, salesfelipe approved these changes

2018-10-16 20:30 UTC, lucis approved these changes

2018-11-05 17:38 UTC, brunojdo approved these changes

2018-11-05 17:40 UTC, merged